### ISSUE TITLE
Neede to modify GFC Docs 

### ISSUE THREAD

**Issue by k-rokk** [NetAppDocs/bluexp-edge-caching#25]
### Page URL

https://docs.netapp.com/us-en/occm38/concept_gfc.html

### Page title

Learn about Global File Cache

### Summary

Please add information about support for Google Cloud NetApp Volumes.  

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
@k-rokk, I am not sure that we have tested and support Google Cloud NetApp Volumes yet.  I have checked with the team and will update the issue when I hear back.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
@k-rokk, I have heard back from the team that we have not yet tested Google Cloud NetApp Volumes. When we do add this support I'll add it into the release notes and other locations in the docs as we do with other new features and support.

Thanks, Tom
