### ISSUE TITLE
BlueXP edge caching Mgmt and Core Server deployment no longer possible via BXP

### ISSUE THREAD

**Issue by placeholger313** [NetAppDocs/bluexp-edge-caching#28]
### Page URL

https://docs.netapp.com/us-en/bluexp-edge-caching/task-gfc-getting-started.html

### Page title

Getting started

### Summary

Hi, 
we just learned that the Global File Cache (EdgeCache) cannot be deployed via BXP anymore. It must be done in a manual process. 
Thx
Holger

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by kholger** [comment]
I was logged in with my private account. This request was opened by me (internal NetApp)

Thx
Holger

**Comment by netapp-tonacki** [comment]
Hi Holger,  Thanks for the information.  I was not aware of this.  I'll check in with Vaishnav who I usually work with to see what's going on and then update the docs.

Thanks, Tom

**Comment by netapp-tonacki** [comment]
Hi Holger,  I'm trying to verify which release pulled this functionality.  Just wanted to let you know I haven't forgotten  :-)

**Comment by netapp-tonacki** [comment]
Hi Holger,  I was told that this info should be pulled from the documentation on May 31st, so that's my plan.  Just wanted to let you know.

**Comment by kholger** [comment]
Great, thanks for the update, Tom!

**Comment by netapp-tonacki** [comment]
I have removed that content from the docs a few days ago.  All set.  Thanks, again for making me aware of this change.
