### ISSUE TITLE
Add Global File Cache (GFC) to document

### ISSUE THREAD

**Issue by Grantglass** [NetAppDocs/bluexp-edge-caching#31]
### Page URL

https://docs.netapp.com/us-en/bluexp-edge-caching/concept-gfc.html

### Page title

Learn about BlueXP edge caching

### Summary

In the last line of the lead, please use Global File Cache (GFC), so Docbot can pull the document correctly. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-tonacki** [comment]
Hi Grant,  The 2 paragraphs in the lead are the following. Where would you like to see this text added? 

"NetApp BlueXP edge caching enables you to consolidate silos of distributed file servers into one cohesive global storage footprint in the public cloud. This creates a globally accessible file system in the cloud that all remote locations can use as if they were local.

BlueXP edge caching is available in two deployment modes to fit your enterprise architecture: as in integrated service combined in a Cloud Volumes ONTAP instance (Cloud Volumes Edge Cache), or as an add-on component to your enterprise storage strategy (Global File Cache)."

**Comment by Grantglass** [comment]
Ideally, we could change the second paragraph to the following:

BlueXP edge caching is available in two deployment modes to fit your enterprise architecture: as an integrated service combined with a Cloud Volumes ONTAP instance, known as Cloud Volumes Edge Cache (CVEC), or as an add-on component to your enterprise storage strategy, referred to as Global File Cache (GFC).

**Comment by netapp-tonacki** [comment]
That works for me.  thanks Grant.  I just happened to be making a change because as of tomorrow we have moved this product to End of Availability.  So this update should be live shortly.
